name: Publish Python Package

on:
  push:
    branches: [ "main" ]  # תהליך יופעל עבור כל דחיפה ל-main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine pytest pytest-mock

      - name: Install package in development mode
        run: python setup.py develop

      - name: Run tests
        run: pytest tests/

      - name: Build the package
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}  # שם המשתמש של PyPI שיוגדר בסודות של GitHub
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}  # סיסמת PyPI שיוגדר בסודות של GitHub
        run: python -m twine upload dist/*
