name: Publish Python Package

on:
  push:
    branches: [ "main" ]
    tags:         # פעולה תתרחש כאשר תג דחוס ל-main
      - 'v*.*.*'  # רק תגיות גרסה בפורמט vX.X.X יפעילו את העלאת החבילה ל-PyPI
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine pytest pytest-mock

      - name: Install package in development mode
        run: python setup.py develop

      - name: Run tests
        run: pytest tests/

      - name: Build the package
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') # העלאה רק עבור דחיפה של תג
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}  # שם המשתמש של PyPI שיוגדר בסודות של GitHub
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}  # סיסמת PyPI שיוגדר בסודות של GitHub
        run: python -m twine upload dist/*
